### PR TITLE
Adapted for JDK17

### PR DESCRIPTION
**Pull request by Furetur**
This PR adapts the H2 benchmark for JDK17. With these changes the H2 benchmark can be built with JDK17.

**Changes**

1. Updated many out of date URLs to Maven repositories
2. Changed derby build config, so it is built using JDK8
3. Added a `jdk8home` property to `default.properties` which is now needed

**How to build**

The build instructions remain unchanged but now the `jdk8home` property must be set and JDK8 also installed.

**About the new _jdk8home_ property**

 Derby is still built with `source=1.8` which requires JDK8 classes on the classpath.

### CODE REVIEW

**Comment by steveblackburn** [comment]
Thanks for this!

Have you checked out the chopin branch?   That is where the upcoming release is.

**Comment by Furetur** [comment]
Sadly, no. I didn't notice it :( Are there any changes related to this PR?

**Comment by steveblackburn** [comment]
The suite is fully updated, so every benchmark is substantially changed (the underlying workload moves from a 2009 version to a 2021 version)   It will be a new major release.

**Comment by Furetur** [comment]
Can you please tell me if the current version of the H2 benchmark on `dev-chopin` is buildable and runnable?

**Comment by steveblackburn** [comment]
Sorry to have left this languishing.  We're now at 2.2.220.

**Pull request closed without merging**
