### PR TITLE
Benchmark calibration and hugedata refactoring

### PR DESCRIPTION
**Pull request by john5f35**
# Summary
This pull request combines both [benchmark calibration](#Benchmark-Calibration) changes 
and [huge data refactoring](#Huge-data-refactoring) changes.

-------------------------------------------------------------------------------------------------------------------------
## Fixes
- fix: eclipse benchmark had the wrong (old) MD5s
- fix: missing and old MD5s for Jython downloads
- fix: broken link for NSIS 3
- remove Maven memory restriction, which caused build to fail on weasel.moma
- add CI caching
- use small size when testing runnability on CI
- add ability to clone and checkout from git repo
- display warning message if build is not a release build

-------------------------------------------------------------------------------------------------------------------------
## Benchmark Calibration
Addresses various calibration issues.

### Performance Numbers
| `default` (s) | `pekania.moma`| `lynx.moma`  |
| :-----------  | :-----------: | :----------: |
| avrora        | 8.026         | 15.465       |
| batik         | 13.763        | 26.245       |
| eclipse       | 10.689        | 17.066       |
| fop           | 2.857         | 4.871        |
| h2            | 10.332        | 19.025       |
| jython        | 10.441        | 26.212       |
| luindex       | 1.263         | 2.109        |
| lusearch      | 2.174         | 2.989        |
| pmd           | 9.694         | 17.799       |
| sunflow       | 10.119        | 23.742       |
| tomcat        | 9.720         | 11.586       |
| tradebeans    | 12.333        | 23.957       |
| tradesoap     | 11.341        | 12.993       |
| xalan         | 10.965        | 19.130       |

#### Avrora
Increased `nodecount` on both default and large to increase workload.

#### Batik
Added a bunch of new SVG files that are between 9MB ~ 40MB to increase the workload.

Note that when running `large` size on `lynx.moma`, >3G heap space (`-Xmx3G` JVM flag) is needed so that it doesn't fail with GC memory exception nor spending too much time in GC.

#### H2
Changed total transactions and scaling for increased workload.

#### Eclipse
Adjusted the tasks to run according to the performance numbers on `fisher.moma`.

To limit running time to ~10sec, instead of doing all tests, only run `setup`, `index`, `search`.

```
size default args "setup", "index", "search"
```

#### FOP
- added a bunch of FOP files from Apache examples; also added one converted from markdown using Laika;
- now loop through all the FOP files in a directory instead of processing one single FOP file;
- removed small size, there is only one default size now.

There has been difficulty in finding large enough FOP files.

#### Jython
- adjusted number of iterations of PyBench to calibrate according to running time on `fisher.moma`.
- removed `large` size due to being repetitive of `default`.

#### PMD
- use directories of sources rather than source list as input to PMD,
  this simplifies the PMD harness, and makes adding and maintaining test sources easier;
- use rule-set names rather than actual files for specifying rule-sets;
- select `default` sources from PMD source, calibrated to around 10 seconds on `fisher.moma`;
- select 500KB+ Java sources from [Eclipse JDT Core](https://github.com/eclipse/eclipse.jdt.core) for `large` size,
  using the same set of rulesets as `default`;
- added a `junit` size which is one file and one ruleset only case,
  but it's interesting in that it actually takes quite a while to process
  this ~600KB Java test file.

#### Tomcat
- increased workload for Tomcat.

#### DayTrader (TradeBeans & TradeSOAP)
- increased workload for both tradesoap and tradebeans;
- use tagged workload names for the 2 benchmarks;
- avoid testing when building daytrader, which makes building daytrader a bit faster.

#### Xalan
- increased workload for default
- removed large size, it's probably not relevant now (doesn't take in big data).

#### LuIndex
- adjusted `default` and `large` size to feed Wikipedia archive to Lucene
- add `--linedoc` and `--dirwalk` option to specify doc-per-line
  format and directory walk;
- add uncompressed Wikipedia archive used for Lucene benchmark;
- modified benchmark harness;
- download and prepare Wikipedia data at build time (if checksum failed)

##### Note
Currently the ~8.5GB `enwiki.txt` is not included in the built jar, but referenced relatively to the scratch directory
(`${SCRATCH}/../bms/luindex/data/luindex/enwiki/enwiki.txt`).
This will be fixed with changes from refactoring large data.

#### LuSearch
- ran `create-queries.pl enwiki-words.txt.gz 11 22` to create 2048 queries of 2048 words each;
- restructured data directory;
- added `index-enwiki`.

#### Sunflow
- modified the original Sunflow benchmark code to generate higher resolution frames 
    (default: 1024 x 1024, large: 4096 x 4096), and include these images in benchmark data.
- also added a constructor that can adjust the error threshold for larger resolutions.
    The inability to do that before caused large size to have unpredictable and high image checking failure rate (with error around 60).
    But then the question is, where is that non-determinism coming from?

-------------------------------------------------------------------------------------------------------------------------
## Huge Data Refactoring

- addresses #144;
- refer and download huge data via GitLab/GitHub raw file access of dacapo-dl repo;
- adds `update-externdata-info` ant target that stores URL and commit hash/tag of dacapo-dl in META-INF at end of build;
- update existing benchmarks to adapt to work with this feature (separate huge data; update build script);
- add `--extdata-install` and `--extdata-set-location` flags;
- use `~/.dacapo-config.properties` to save the location of unpacked data directory;
- versioned local huge data management based on the `Implementation-Version` of dacapo jar,
    so that the local huge data directory will be `${user-specified-extdata-dir}/${dacapo-version}/dat`;
- use `${DATA}` in benchmark config file to refer to files in external data;
- by default `${DATA}` is resolved to `${dacapo-parent}/data/${dacapo-version}/dat`,
    otherwise the saved location in `~/.dacapo-config.properties`;
- supports externally packaged libs/jars by first searching the external data directory 
    (`${dacapo-parent}/data/${dacapo-version}/jar`),
then scratch if not found;
- checks per-file MD5 integrity when running with `--extdata-set-location` flag;
- also fixes a relative path output problem in `luindex`.

## Documentation
At build-time specify the *raw* URL and Git commit hash/tag in `dacapo.properties`:
```
dacapo-dl.url.raw=https://gitlab.anu.edu.au/dacapo/anu-dev/dacapo-dl/raw
# or
# dacapo-dl.url.raw=https://raw.githubusercontent.com/dacapobench/dacapo-dl/

dacapo-dl.commit=HEAD
```

These information will be built into the dacapo jar by the `update-externdata-info` ant target,
which will be run at the end of build (or can be run separately).

### Installing external data
The files need to be downloaded are specified in `META-INF/dlfiles.list` in dacapo-dl repo.
Those files will be downloaded, and each should be accompanied by an MD5 check.

Two flags have been added to the commandline interface with regard to the external data.
```
--extdata-install <intall_path>           Download and install
                                          external data.
--extdata-set-location <ext_data_loc>     Path to external data
                                          location. Note, this
                                          directory should
                                          contain"data" and "jar"
                                          sub-directories.
```

The user can download and install the external data by using the `--extdata-install` command.
This will download the external data according to the URL embedded in manifest to `${ext_data_loc}`, 
check the MD5 sum, unpack, and set the location to `${ext_data_loc}`.

NOTE: the downloaded zips are not deleted, the user may want to delete them manually.

##### set location
The `--extdata-set-location` assumes that the user has the data package downloaded and unpacked on the local machine.
It will check the MD5 integrity of the local data, and records its location.

It will give a warning if the MD5 integrity check fails.

##### MD5 checking
When setting the location of the external data/resource with `--extdata-set-location` flag,
DaCapo will check against an included MD5 list file, `dacapo.jar!/META-INF/huge-data-md5s.list`, the MD5 of every expected file in the list under the target directory.
This is to ensure that the user has kept the data integrate.

If the checksum failed, it will still set the directory location, but with the following warning message:
```
WARNING: MD5 checking failed. Your huge data does not match expected release.
Please download and install the latest huge data using --extdata-install flag;
otherwise please note the changes in research publication.
```

##### Versioned local data
The local data download directory is versioned.
So if the user uses `/path/to/extdata` as the local external data installation directory (`--extdata-install /path/to/extdata`),
a subdirectory `/path/to/extdata/${dacapo-version}` will be created based on the `Implementation-Version` stored in the dacapo jar.

This is to allow multiple data (and supporting lib jars) to coexist with multiple versions of dacapo jar on a local machine.

##### remembering the location
The location will be written to `~/.dacapo-config.properties` file:
```
#
#Thu Jun 28 15:12:45 AEST 2018
Extern-Data-Location=/tmp/data
```
This file is read when resolving the location of data directory.

### Using external data
Benchmarks can reference the external data in their size configuration, for example:
```
size default args "${DATA}/luindex/william","${DATA}/luindex/kjv"
  output stdout  digest 0xc90792fce1594b4b9ea1b01d593aefe801e6e58b,
         stderr  digest 0xda39a3ee5e6b4b0d3255bfef95601890afd80709,
	 "index/segments_1"  bytes 136;
```

In `Config.preprocessArgs()` (called by all benchmarks), `${DATA}` will be replaced by the resolved data directory.
This function will also check the existence of the file under the data directory.
When the referenced file is not found, it will call `ExternData.failDataNotFound()`, which prints out the following and exits with `-1`.
```
ERROR: failed to find external data for size 'small'.
Please check that you have installed the external data properly (current: /tmp/data)
Please run DaCapo with `--extdata-install` flag to download and install the external data,
or with `--extdata-set-location` to set the location of unpacked external data directory.
```

`${DATA}` will be resolved according to the following:
- if `Extern-Data-Location` cannot be found in `~/.dacapo-config.properties`, it will be resolved to `${dacapo-parent}/data`, where `${dacapo-parent}` is where `dacapo.jar` resides;
- otherwise, it is resolved to `${Extern-Data-Location}/data`.

#### Jar dependencies
Jar dependency can be optionally packaged externally and installed to `${Extern-Data-Location}/jar`.

For each jar dependency in the benchmark, first search through the above external data jar path,
then search `scratch/jar` if not found. This way it supports gradual transition of moving all the jars out of DaCapo target jar.

An error message similar to the above is printed if a jar dependency is not found.

### Other
This merge request also fixes a problem in `luindex` where the relatived path is calculated from the scratch directory only.
In the above example config that uses the data directory this will not work.
This behaviour has been fixed by choosing between scratch and data based on the path prefix.

### CODE REVIEW

**Comment by john5f35** [comment]
NOTE: currently there is a problem with pushing to the dacapo-dl repo on GitHub due to `luindex-huge.zip` being 2.9GB which is over the single-file size limit placed by GitHub (2GB). The ANU dacapo-dl repo is publicly accessible, so the reference in `dacapo.properties` still points to the [mirror repository on ANU GitLab](https://gitlab.anu.edu.au/dacapo/anu-dev/dacapo-dl).

**Comment by john5f35** [comment]
This oversize issue has been fixed by splitting the `enwiki.txt` into two and re-zip them.

**Comment by john5f35** [comment]
This oversize issue has been fixed by splitting the `enwiki.txt` into two and re-zip them.

**Comment by john5f35** [comment]
- fixed warning message;
- fixed `luindex` huge data no `stdout` output issue;
- added 3f3bf15 and ffbd938, which now points `dacapo-dl` to GitHub, and implements a walk-around/solution to deal with GitHub respond with 503 sometimes when trying to download huge data (probably due to downloading huge data in quick succession).

**Comment by steveblackburn** [comment]
Merged

**Pull request closed without merging**
