### PR TITLE
Add debug symbols to Harness.class

### PR DESCRIPTION
**Pull request by aoli-al**
Currently Harness.class is compiled without debug symbols. This PR adds this information back.

### CODE REVIEW

**Comment by steveblackburn** [comment]
Thanks for the PR.  I appreciate it.

You didn't explain the motivation for wanting to upstream this change.   Can you please elaborate?

**Comment by aoli-al** [comment]
Thanks for maintaining this great project! I tried to use debugger to understand how dacapo works. The debug symbol for this file is missing so I think it is a good idea to add it back.

**Comment by steveblackburn** [comment]
Thanks for that.

Just to be clear: javac has these options turned off _by default_, not for our project, but _for all java compilation_.  It is thus completely normal to have debugging turned off.  The suite has about 15 M lines of code and I expect almost all of it will have debugging turned off (ie default).   Nearly all of that code is not maintained by me, but by the upstream maintainers, so I'm in no position to change it.  There are costs associated with including debugging info, which is why javac has it off by default.

If you want to debug the Harness itself, then you should be able to do so without the symbols, since you have access to the source.  On the other hand, if for some reason you feel you would like symbols in the harness, I suggest that you make yourself a local build of the suite with debugging turned on, as you've done.

I'm afraid my basic principle is not to deviate the default behavior of javac unless there's a very strong reason to do so.  In this case it is best if you make the change locally.

I hope that make sense!   Thanks for engaging with the project.

**Comment by aoli-al** [comment]
Thanks for your clarification!

> javac has these options turned off by default.  It is thus completely normal to have debugging turned off. 

This is not true. If you run `javac Main.java`, you will see LineNumberTable in the class file. Only `ant` disabled line number table by default. For Maven and Gralde, they both enable line number table by default. So the default bevahiour of javac is actually to include line number node. 

>  The suite has about 15 M lines of code and I expect almost all of it will have debugging turned off (ie default). 

This is not true either. Since dacapo uses upstream build tools (maven/gradle) to build libraries, many projects have line number table enabled by default. I've checked `batik`, `lucene`, and `avrora` and I can see that the line number nodes are enabled for all of them. 

It seems that Harness.java is the only file that misses line numbers (e.g. https://github.com/dacapobench/dacapobench/blob/main/benchmarks/harness/build.xml#L153C1-L153C180) Thus, it would be good to change `Harness.java` for consistency. 

Anyway, I do appreciate your effort in maintaining such a great benchmark, and I would respect your decision. I hope this comment explains my intention better. Thanks!

**Comment by steveblackburn** [comment]
I see.

Let me try to capture what I think your actual concern is....

By default, **javac includes line and source file debug information** ([as per the oracle docs](https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html)).

However, by default, **ant includes no debug information**.

Therefore in the cases we're compiling via ant, we have less debug information than the default.  This concern makes sense.  

However, I think if that's the concern, then the right solution is:
1. to be systematic, rather than just target one file
2. to use the same debug levels as the javac default (lines, files).

**Comment by aoli-al** [comment]
This patch only modifies one file because `Harness.java` is the only file that misses this information:

https://github.com/dacapobench/dacapobench/blob/main/benchmarks/harness/build.xml#L153
https://github.com/dacapobench/dacapobench/blob/main/benchmarks/bms/avrora/build.xml#L27
https://github.com/dacapobench/dacapobench/blob/main/benchmarks/bms/common.xml#L178
https://github.com/dacapobench/dacapobench/blob/main/benchmarks/bms/common.xml#L187

So this patch is enough to make the compilation process consistent.

**Comment by steveblackburn** [comment]
OK. Thanks for this.  I appreciate your engagement.

For future reference, it would have helped if you'd been clearer in your initial PR, pointing out as you have now, that the way the DaCapo ant scripts deal with Harness was an outlier.

**Pull request merged**
