### PR TITLE
Create standalone launcher jars

### PR DESCRIPTION
**Pull request by liufengyun**
## Motivation

This PR adds standalone launchers for benchmarks. The main motivation is to make it easier to run the benchmarks with AOT (Ahead-Of-Time) Java compilers, such as [Native Image](https://www.graalvm.org/).

Currently, DaCapo uses custom class loader at runtime to dynamically load the JARs for a benchmark. However, for AOT compilers, it is mandatory to supply all JARs of a benchmark as input to the compiler. The launcher JARs are introduced to solve the problem.

## Launcher Jars

A launcher JAR is a JAR that only contains a specification of all actual JARs and the main class of a Java application.

For example, the launcher JAR for `sunflow` only contains the file `META-INF/MANIFEST.MF`:

```
Manifest-Version: 1.0
Main-Class: Harness
Class-Path: ../jar/lib/janino/janino-2.5.15.jar ../jar/sunflow/sunflow-
 0.07.2.jar ../../dacapo-evaluation-git-82543f43.jar
```

The manifest file above contains all the JARs needed for the `sunflow` benchmark. The Native Image compiler is able to consume the manifest file thus get all JARs for the AOT compilation of sunflow.

In the distribution, the launcher JARs are located in the directory `launchers` after unzip:

```
dat/       jar/       launchers/
```

## Usage with Java

To run the benchmark with `java`, it suffices to issue the following command:

```
java -jar path/to/launchers/sunflow.jar sunflow
```

## Usage with Native Image

To compile the launcher JAR with Native Image, we need to first run the agent to collect the meta
data about reflections and resources:

```
path/to/graalvm/bin/java -agentlib:native-image-agent=config-output-dir=./dacapo -jar  path/to/launchers/sunflow.jar sunflow
```

With the refleciton configuration collected under the directory `./dacapo`, we can now compile it with Native Image:

```
path/to/graalvm/bin/native-image -H:ConfigurationFileDirectories=./dacapo -jar path/to/launchers/sunflow.jar
```

Now we can run the compiled executable:

```
./sunflow sunflow
```

##  Implementation

We tried to minimize the changes to Dacapo --- the build workflow is exactly the same as before.

The main change is that we added a python script to create the launcher JAR when building the
distribution of a benchmark.

The python script only depends on a built-in library `zipfile` of Python. We have checked that it is
present for all active releases of Python from `3.8` to `3.12`.

## Test Result

We checked that the standalone launchers can work with Java, except the following benchmarks:

- cassandra
- h2o
- tradebeans
- tradesoap

For Native Image, currently the follow benchmarks work:

- avrora
- batik
- biojava
- fop
- graphchi
- h2
- luindex
- lusearch
- pmd
- sunflow
- xalan

We are working on making more benchmarks work with Native Image with proper Native Image compilation and/or runtime options.

### CODE REVIEW

**Comment by liufengyun** [comment]
@steveblackburn In terms of the 4 launchers that do not work currently, the benchmarks `cassandra` and `h2o` do not work with JDK 21 even without the standalone launchers:

- cassandra
- h2o

The only problem seems to be with the following two:

- tradebeans
- tradesoap

 The error messages for the two are similar:

```
Using scaled threading model. 10 processors detected, 10 threads used to drive the workload, in a possible range of [1,2048]
Version: daytrader svn-1904225 wildfly 26.1.3.Final (use -p to print nominal benchmark stats)
DayTrader is using port 8080 (8080+0). Configure with -Djboss.http.port and/or -Djboss.socket.binding.port-offset
NOTE: Starting watchdog timer with timeout of 110 seconds. Adjust timeout with the -f command line option.
INFO  [org.jboss.modules] JBoss Modules version 2.0.2.Final
java.lang.IllegalStateException: The LogManager was not properly installed (you must set the "java.util.logging.manager" system property to "org.jboss.logmanager.LogManager")
        at org.jboss.logmanager@2.1.18.Final//org.jboss.logmanager.Logger.getLogger(Logger.java:57)
        at org.jboss.as.server@18.1.2.Final//org.jboss.as.server.Main.main(Main.java:90)
        at org.jboss.modules.Module.run(Module.java:353)
        at org.jboss.modules.Module.run(Module.java:321)
        at org.jboss.modules.Main.main(Main.java:604)
        at org.dacapo.daytrader.DaCapoServerRunner.initialize(DaCapoServerRunner.java:32)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.dacapo.daytrader.Launcher.initialize(Launcher.java:80)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.dacapo.harness.Tradebeans.prepare(Tradebeans.java:90)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:229)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at Harness.main(Harness.java:39)
FATAL [org.jboss.as.server] WFLYSRV0239: Aborting with exit code 1
```

It happens even after setting `-Djava.util.logging.manager=org.jboss.logmanager.LogManager` explicitly:

```
java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar dacapo-evaluation-git-ec9f58c5/launchers/tradebeans.jar tradebeans
```

I did some investigation, but could not find anything useful with Google. Have you experienced similar issues with `tradebeans` and `tradesoap`?

**Comment by steveblackburn** [comment]
Thanks for this.

All benchmarks have been extensively tested on a variety of 21 runtimes, so you should not be experiencing problems. 

First, Cassandra and h2o *do* work with 21, *but* due to respective upstream issues they require special settings when used with 21.  DaCapo will detect whether the settings are right and raise an error if not. You should see this in the respective error messages.  Please try that and let me know if you still have issues. 

I'm not sure why you're having issues with the trade benchmarks. I will take a closer look as soon as I have the opportunity. 

Sorry for the slow response. I'm a little overwhelmed with deadlines and travel :)

**Comment by liufengyun** [comment]
Thank you @steveblackburn . With your helpful input, now I can confirm the launchers for `h2o` and `cassandra` work with Java 21.

I used the following commands:

```
    java -Dsys.ai.h2o.debug.allowJavaVersions=21 -jar dacapo-evaluation-git-4fcc490c/launchers/h2o.jar h2o

    java -Djava.security.manager=allow -jar dacapo-evaluation-git-4fcc490c/launchers/cassandra.jar cassandra
```

The launcher for `h2o` works on both Linux-AMD64 and Mac-AARCH64, while `cassandra` only works on Linux-AMD64. We primarily care about the Linux-AMD64 platform, so MAC-AARCH64 is not an issue.

So the two remaining launcher JARs that do not work with Java is `tradesoap` and `tradebeans`. I'm still in the process of investigation.

**Comment by steveblackburn** [comment]
Thank you @liufengyun!

**Pull request merged**
